# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(948, 323)
        self.pushButtonNew = QtWidgets.QPushButton(Form)
        self.pushButtonNew.setGeometry(QtCore.QRect(620, 80, 98, 27))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 270, 771, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelDescription_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelDescription_2.setObjectName("labelDescription_2")
        self.horizontalLayout_6.addWidget(self.labelDescription_2)
        self.lineEditDescription = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditDescription.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.horizontalLayout_6.addWidget(self.lineEditDescription)
        self.pushButtonPrint = QtWidgets.QPushButton(Form)
        self.pushButtonPrint.setGeometry(QtCore.QRect(730, 40, 98, 27))
        self.pushButtonPrint.setObjectName("pushButtonPrint")
        self.pushButtonDelete = QtWidgets.QPushButton(Form)
        self.pushButtonDelete.setGeometry(QtCore.QRect(840, 80, 98, 27))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonAccept = QtWidgets.QPushButton(Form)
        self.pushButtonAccept.setGeometry(QtCore.QRect(620, 150, 98, 27))
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.pushButtonEdit = QtWidgets.QPushButton(Form)
        self.pushButtonEdit.setGeometry(QtCore.QRect(730, 80, 98, 27))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 230, 561, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelSortKey_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelSortKey_2.setObjectName("labelSortKey_2")
        self.horizontalLayout_7.addWidget(self.labelSortKey_2)
        self.lineEditSortKey = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditSortKey.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditSortKey.setObjectName("lineEditSortKey")
        self.horizontalLayout_7.addWidget(self.lineEditSortKey)
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 146, 561, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelHash_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelHash_2.setObjectName("labelHash_2")
        self.horizontalLayout_8.addWidget(self.labelHash_2)
        self.lineEditHash = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEditHash.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditHash.setObjectName("lineEditHash")
        self.horizontalLayout_8.addWidget(self.lineEditHash)
        self.labelDirectory = QtWidgets.QLabel(Form)
        self.labelDirectory.setGeometry(QtCore.QRect(10, 10, 921, 21))
        self.labelDirectory.setObjectName("labelDirectory")
        self.pushButtonClear = QtWidgets.QPushButton(Form)
        self.pushButtonClear.setGeometry(QtCore.QRect(620, 190, 98, 27))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 190, 561, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelSymbol_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.labelSymbol_2.setObjectName("labelSymbol_2")
        self.horizontalLayout_9.addWidget(self.labelSymbol_2)
        self.lineEditSymbol = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEditSymbol.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditSymbol.setObjectName("lineEditSymbol")
        self.horizontalLayout_9.addWidget(self.lineEditSymbol)
        self.pushButtonShowList = QtWidgets.QPushButton(Form)
        self.pushButtonShowList.setGeometry(QtCore.QRect(840, 40, 98, 27))
        self.pushButtonShowList.setObjectName("pushButtonShowList")
        self.pushButtonWrite = QtWidgets.QPushButton(Form)
        self.pushButtonWrite.setGeometry(QtCore.QRect(620, 40, 98, 27))
        self.pushButtonWrite.setObjectName("pushButtonWrite")
        self.layoutWidget_5 = QtWidgets.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(13, 80, 555, 41))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_3.setMaximumSize(QtCore.QSize(267, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.comboBoxHash = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBoxHash.setMinimumSize(QtCore.QSize(371, 32))
        self.comboBoxHash.setObjectName("comboBoxHash")
        self.horizontalLayout_10.addWidget(self.comboBoxHash)
        self.pushButtonStop = QtWidgets.QPushButton(Form)
        self.pushButtonStop.setGeometry(QtCore.QRect(730, 150, 98, 27))
        self.pushButtonStop.setObjectName("pushButtonStop")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonNew.setText(_translate("Form", "new"))
        self.labelDescription_2.setText(_translate("Form", "description"))
        self.pushButtonPrint.setText(_translate("Form", "print"))
        self.pushButtonDelete.setText(_translate("Form", "delete"))
        self.pushButtonAccept.setText(_translate("Form", "accept"))
        self.pushButtonEdit.setText(_translate("Form", "edit"))
        self.labelSortKey_2.setText(_translate("Form", "sort key                                  "))
        self.labelHash_2.setText(_translate("Form", "unique hash = latex name"))
        self.labelDirectory.setText(_translate("Form", "directory"))
        self.pushButtonClear.setText(_translate("Form", "clear"))
        self.labelSymbol_2.setText(_translate("Form", "math symbol in latex"))
        self.pushButtonShowList.setText(_translate("Form", "show list"))
        self.pushButtonWrite.setText(_translate("Form", "write"))
        self.label_3.setText(_translate("Form", "latex name                             "))
        self.pushButtonStop.setText(_translate("Form", "stop"))
